name       : xdg-desktop-portal
version    : 1.16.0
release    : 23
source     :
    - https://github.com/flatpak/xdg-desktop-portal/releases/download/1.16.0/xdg-desktop-portal-1.16.0.tar.xz : 5b41a5915c11851493d8c33b9783f147a0a6f419db80ad760e84cd3420fd8c19
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Desktop integration portal
description: |
    A portal frontend service for Flatpak and possibly other desktop containment frameworks. xdg-desktop-portal works by exposing a series of D-Bus interfaces known as portals under a well-known name (org.freedesktop.portal.Desktop) and object path (/org/freedesktop/portal/desktop). The portal interfaces include APIs for file access, opening URIs, printing and others.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(fontconfig)
    - pkgconfig(fuse3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libportal)
    - docbook-xml
    - xmlto
setup      : |
    %patch -p1 < $pkgfiles/0001-Only-return-found-implementation-if-it-launched.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
