name       : xdg-desktop-portal
version    : 1.14.5
release    : 19
source     :
    - https://github.com/flatpak/xdg-desktop-portal/releases/download/1.14.5/xdg-desktop-portal-1.14.5.tar.xz : 0deecc8a9fa6ab958b5a68d2ec45210c964307ae9d86343a461dad45b1220fdd
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Desktop integration portal
description: |
    A portal frontend service for Flatpak and possibly other desktop containment frameworks. xdg-desktop-portal works by exposing a series of D-Bus interfaces known as portals under a well-known name (org.freedesktop.portal.Desktop) and object path (/org/freedesktop/portal/desktop). The portal interfaces include APIs for file access, opening URIs, printing and others.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(fontconfig)
    - pkgconfig(fuse3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libportal)
    - docbook-xml
    - xmlto
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
